repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Format (backend & client)
        entry: uv run ruff format
        args: ["backend", "client"]
        language: system
        pass_filenames: false
